version: "3.5"

services:
  portifolio-sairan:
   container_name: portifolio-sairan
   image: sairan/portifolio:latest
   ports:
    - "3001:3001"
   restart: always
   networks:
      - proxy-reverse-network

networks:
  proxy-reverse-network:
    name: proxy-reverse-network
    external: true